name: Build and upload jar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Build
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: ServerRestarts
          # A file, directory or wildcard pattern that describes what to upload
          path: build/libs/*.jar
          if-no-files-found: error
